name: ballotbox
version: "1.0.0"

profile: "ballotbox"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ballotbox:
    # Config indicated by + and applies to all files under models/example/
    +materialized: table
